### ISSUE TITLE
Uncraftable ducts?

### ISSUE THREAD

**Issue by lotrzykjp** [TheLimePixel/GregBlock#74] opened 2018-11-18 17:49 UTC
I've been doing those earlier but now the recipe just dont work(moving items option from jei seems to detect that everything is alright), im using tin hardened glass and cobalt tools except wrought iron hammer,
(cobalt one doesnt works too anyway)

**Comment by lotrzykjp** [comment] 2018-11-18 17:50
![item2](https://user-images.githubusercontent.com/30722968/48676139-c341ec80-eb62-11e8-9d16-b816618a0b93.png)
![item](https://user-images.githubusercontent.com/30722968/48676140-c3da8300-eb62-11e8-9547-03c585f779ca.png)
![flu](https://user-images.githubusercontent.com/30722968/48676141-c3da8300-eb62-11e8-99ad-acc51c9881a6.png)

**Comment by TheLimePixel** [comment] 2018-11-18 19:03
Duplicate of #6

**Closed as completed by TheLimePixel** 2018-11-18 19:03 UTC
Labels: duplicate
